server:
  port: 8083

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  application:
    name: apigateway-service

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**
        - id: feed-service
          uri: lb://FEED-SERVICE
          predicates:
            - Path=/api/feeds/**
        - id: post-service
          uri: lb://POST-SERVICE
          predicates:
            - Path=/api/posts/**